name: Publish pre-release version

on:
  workflow_dispatch:
    inputs:
      BASELINE:
        description: 'Baseline branch'
        required: true
        default: 'develop'

jobs:
    build:
        if: "!contains(github.event.head_commit.message, 'skip ci')"
        runs-on: ubuntu-latest

        steps:
            - name: Determine Checkout Ref / Is Workflow Dispatch
              if: github.event_name == 'workflow_dispatch'
              run: echo "BRANCH_REF=${{ github.event.inputs.BASELINE }}" >> $GITHUB_ENV

            - name: Checkout
              uses: actions/checkout@v2
              with:
                  submodules: recursive
                  token: ${{ secrets.GITHUB_TOKEN }}
                  ref: ${{ env.BRANCH_REF }}
                  fetch-depth: 0

            - name: Use Node.js 14.x
              uses: actions/setup-node@v2
              with:
                  node-version: 14.x
                  registry-url: 'https://registry.npmjs.org'

            - name: Configure Git User
              run: |
                  git config --global user.email "ci@glyph.com"
                  git config --global user.name "ci@$GITHUB_ACTOR"

            - name: yarn install, build
              run: |
                  yarn --no-lockfile
                  yarn build

            - name: Create release version
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
                yarn semantic-release
                npx semantic-release

